language: node_js
node_js:
  - "10"
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - npm install -g @angular/cli
  - npm install
script:
  - ng lint
  - ng test --browsers ChromeHeadless --watch=false --progress=false
  - ng build --prod --aot
