version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing cmd tools for build
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo Building Screenforce Frontend
      - ng build -c development
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: dist/screening-ui-gen/
