import {Bucket} from '../entities/Bucket';

export const BUCKETS: Bucket[] = [
    { bucketId: 1,
      bucketDescription: 'OCA level Java questions',
      isActive: true,
    },
    { bucketId: 2,
      bucketDescription: 'SQL database questions',
      isActive: true,
    },
    { bucketId: 3,
      bucketDescription: 'JavaScript questions',
      isActive: true,
    },
    { bucketId: 4,
      bucketDescription: 'JavaScript questions',
      isActive: true,
    },
    { bucketId: 5,
      bucketDescription: 'JavaScript questions',
      isActive: true,
    },
    { bucketId: 6,
      bucketDescription: 'JavaScript questions',
      isActive: true,
    },
    { bucketId: 7,
      bucketDescription: 'JavaScript questions',
      isActive: true,
    }
  ];
